### ISSUE TITLE
Move reinsurance risk_level from reins scope into reins info file

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OpenDataStandards#21]
There is currently more flexibility in OED financial fields than can be supported by the Oasis Financial Module. One of those flexibilities is the ability to specify mixed risk levels in the scope of a reinsurance treaty. 

For example, a Surplus share treaty could have as separate lines in the reins scope file
risk_level 'loc' LocNumber 1, Ceded percent 0.1
risk_level 'pol' PolNumber 5, Ceded percent 0.2

My suggestion is that if mixed risk levels do not occur in practice and treaties tend to have just one risk level defined, then to move the risk_level into the reinsurance_info file, so that just one risk level per contract can be specified.  

Making reasonable restrictions on the data entry to align with the supported financial features will reduce data processing errors and simplify validation.

Note that a very useful feature of OED reinsurance scope is the ability to define a 'LocGroup' risk level, which can be any group of locations. this can be used to generically model mixed risk level scope treaties, if they exist.

**Comment by MattDonovan82** [comment]
@johcarter got this reply from Anya at GC and have also asked Swiss re:

Hi Matt,
 
Thank you for your question.  As with all things reinsurance, the answer is never a simple “yes” or “no”.
 
Per Risk Excess of Loss treaties are the only commonplace treaty type that are problematic in this regard.  They apply at the “risk” level.  This means different things to different primary companies and can even apply differently from one policy to the next.  In general, at least in the North American market, the definition of “risk” is at the primary company’s sole discretion.  However, the good faith aspect of our business means that, for a given Per Risk treaty, “risk” can’t be defined completely arbitrarily and inconsistently from one claim to the next, or from one year to the next.
 
When it comes to modeling, this is generally handled by the vendor models as a binary choice, either apply the treaty at the location level or at the policy level.  Companies have to code their data to strike a balance between recognizing separate buildings and their primary characteristics (including address) and reflecting how the reinsurance responds.  A line of business that often has this issue is Farm Property exposures.
 
A few cat model vendors have an input that allows the user to specify a “number of buildings” parameter at the location level, which tightens the loss distributions somewhat, reducing tail losses, but does not permit reinsurance to be applied at the “building” level.

**Comment by johcarter** [comment]
Implemented in branch https://github.com/OasisLMF/OpenDataStandards/tree/feature/oed-schema-changes

**Comment by MattDonovan82** [comment]
added to release candidate for v2.0.0
