### ISSUE TITLE
Additional occupancy code in OED- railway buildings

### ISSUE THREAD

**Issue by delioma** [OasisLMF/OpenDataStandards#27]
Hi Matt and Aiste

This is  a request concerning occupancies. We have railways-related assets to represent, including railway bridges, railway tunnels and commercial-type exposure associated to railways like station buildings, offices, warehouses, repair buildings, etc.

We will be using occupancy “Transportation, Railroad” (1251) in combination with Construction code 5550 (Tunnels, Unknown Tunnel) and Construction code 5400  (Bridges, Unknown Bridge) to specify railway tunnels and railway bridges, respectively.

For railway-related commercial buildings, we would like adding an extra Commercial occupancy code; e.g. 1124 (Commercial, Railway buildings), if possible.

I had initially looked at Miscellaneous, Railway Property (construction code: 5951); however this comprehends “railway stations, railway tunnels, railway bridges, railway tracks, and cables along the tracks but excluding trains.”- I don’t think this includes buildings, and also it does not allow for separation of the railway-related structures that we need for our modelling purposes.

Look forward to your advice.

Thanks and best regards,
Delioma

**Comment by MattDonovan82** [comment]
Email string:

Hello Delioma,
 
Your proposal to use occupancy and construction combinations looks great to me.
 
As for adding the new Railway building occupancy, I would like to clarify first. How are these railway buildings different from other buildings? I.e. I assume railway building have some buildings that are used as offices, some as warehouses, some might be parking spaces (rather building), some repair buildings. Other than they belong to a railway company, would their vulnerabilities be different from any other building of the same type that doesn’t belong to a railway company?
 
Regards,
Aiste

**Comment by MattDonovan82** [comment]
Hi Aiste
 
Many thanks for your prompt reply.
 
In most cases I agree that railway buildings will be similar to other commercial buildings; although we do have some specific types like “galleries” that are not found in other commercial types. Another reason is that in our model we need to be able to separate them out because we have model information that tells us where those buildings are likely to be located, in the absence of detailed location info provided in the client portfolios, so we need to provide separate codes.
 
If you agree with the above then, I propose to code them as  1124 (Commercial, Railway buildings).
 
Look forward to your thoughts.
 
Thanks and regards,
Delioma

**Comment by MattDonovan82** [comment]
Thanks Delioma,
 
In that case, it makes sense to add a new code.
 
Regards,
Aiste

**Comment by MattDonovan82** [comment]
@delioma to confirm we are adding just thew one extra code of 1124 - Commercial Railway buildings?

**Comment by MattDonovan82** [comment]
New occ code 1124 added in v1.1.5 - closed

**Comment by delioma** [comment]
Thanks Matt. Suggested description: Commercial, Railway buildings (station building, gallery, etc)
