### ISSUE TITLE
PERILS to OED Conversion

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/OpenDataStandards#31]
Question: 

What is the best way to accommodate PERILS IED that is aggregated to CRESTA? 

Shall we add the following proposed fields to the loc file (examples for Thailand)? 

Proposed Headers: 

* CRESTA_Desc (Bangkok, Nonthaburi etc)
* CRESTA_ID (THA_10, THA_11 etc) 

or 

Use the Geogschemes 'CRH' (High Res CRESTA) and 'CRL' (low res CRESTA) and corresponding 'Geogname'?

**Comment by MattDonovan82** [comment]
If the Geogscheme/name are used, we may only need to add one new field for CRESTA_ID?

**Comment by aiste-kalinauskaite** [comment]
Use GeogScheme and GeogName fields. Due to different spellings, usually modellers use only what you define as CRESTA_ID (that's what would go in GeogName). Is description relevant (could be a multitude of different spellings)? If the names are relevant, another user defined Geogscheme could be used, or LocUserDef fields, as I think this could only have relevance in reporting, not so much in modelling itself.

**Comment by MattDonovan82** [comment]
Joh and I have been talking about this off line too and a few Geogscheme/names might be required to identify the high res and low res. We agree that the CRESTA_ID is probably the most important field for any modelling purposes but description will still need to be captured for reporting, so using one of the other user defined fields should be ok.

**Comment by MattDonovan82** [comment]
have put together an example with comments on how to code the PERILS data using OED. Please take a look and let me know your suggestions before I send back to PERILS. Thanks.
[OED_PERILS_Example_v0.1.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/6458280/OED_PERILS_Example_v0.1.xlsx)

**Comment by MattDonovan82** [comment]
any suggestions on the OED headers proposed in the excel sheet @johcarter @aiste-kalinauskaite before I send back to PERILS?

**Comment by aiste-kalinauskaite** [comment]
@MattDonovan82 
Using AA1 for perils that are not in OED would mean that those exposures would be counted towards all of the perils (flood, windstorm, earthquake, hail, etc). There are no models in Oasis for volcanic eruptions or sewer backup, so I wouldn't recommend adding new codes, unless there is a need for it.
On perils, does earthquake in PERILS mean just ground shake? Or does it include other subperils listed in OED? If the latter,t he code would need to be updated.
CountryCode would need to be converted to the two character ISO2A codes. 
LocUserDef3 (or any other user defined fields) are not used by models. So if Total TIV is saved there, it's just for information. We currently do not have models that could work just of the Total TIV value, so it would need to be split into other fields (Building, Contents, Other, BI TIV) in order to be used.
Note on deductibles, LocDedType6All should be used as well with the correct value, depending if deductibles are amounts or percentages of TIV or loss.
Equivalently, use LocLimitType6All for limits.

**Comment by MattDonovan82** [comment]
thanks for the feedback @aiste-kalinauskaite. I will include these points and questions.

**Comment by johcarter** [comment]
Generally agree with Aiste's points, @MattDonovan82. 

About the peril codes that are not covered and whether there is a need for it - there may be other reasons other than the existence of models for these perils (such as converting tools into and out of other exposure data formats) so I would raise that as a question.

**Comment by MattDonovan82** [comment]
Have mapped data fields and sent back to PERILS

**Comment by MattDonovan82** [comment]
Re-Opening the original Issue:

We're looking to create a conversion script/tool that can be housed on this repo to convert PERILS IED data into OED format.
It will allow the user to convert the EPRILS data themselves or PERILS to convert it themselves so the user can download the data already in OED format.

The three PERILS data templates that are available are attached here. They vary slightly depending on the region and the tabs in red are the only tabs that need converting - all others have been blanked out but will still be present in the spreadsheet for the user. The spreadsheets need to remain in this format. The column headers for each currency are the same and can be duplicated and the best OED field has been added underneath in yellow. 

There are still some questions in the comments as some OED fields do not exist for the upper and lower ranges of limits for example. Would flexifields best to be used here? If so, more will need to be added to OED The 'UserDef' fields are being used for the 'Cresta definitions'. Any suggestions of alternatives would be useful. These will be reporting/data storage purposes only.

The peril and country codes have also been attached for the mappings.

It's worth noting that the 'Low Res' and 'high res' should be 'CRL' or 'CRH' in the Geogscheme1 field.

**Comment by MattDonovan82** [comment]
[PERILS_OED_Header_Mapping_v0.1.xlsx]
(https://github.com/OasisLMF/OpenDataStandards/files/7100473/PERILS_OED_Header_Mapping_v0.1.xlsx)

Could someone possibly try and look into this conversion tool ASAP? I've spoken to Joh and we've agreed on the most appropriate OED fields to use. The attached mapping doc shows the current PERILS fields with the OED fields underneath. The blue fields represent new columns and the data needs to remain in the original format.

The conversion tool/code needs to be simple enough to run and install on local machines.

Happy to chat further if necessary.

**Comment by benhayes21** [comment]
created a simple script here

https://github.com/OasisLMF/OpenDataStandards/tree/feature/31_perils_to_oed_conversion/OpenExposureData/tools/perils_conversion

**Comment by MattDonovan82** [comment]
PERILS have committed to creating the macro for the front end on the conversion done in python by @benhayes21. Closed as will be developed by PERILS in the coming months.
