### ISSUE TITLE
LocPopulation xlsx file in Readme returns 404 error

### ISSUE THREAD

**Issue by pzwsk** [OasisLMF/OpenDataStandards#86]
the following file returns a 404 error:
https://github.com/OasisLMF/OpenDataStandards/blob/master/OpenExposureData/Example_inputs/pi_wind/OED_LocPopulation_v2.0.0.xlsx

**Comment by benhayes21** [comment]
moved to here https://github.com/OasisLMF/OpenDataStandards/blob/master/OpenExposureData/Docs/OED_LocPopulation.xlsx

**Comment by benhayes21** [comment]
@MattDonovan82 to update the readme with the new link

**Comment by MattDonovan82** [comment]
@pzwsk I've actually removed the link from the read me because the 'loc_population' fields are being included in the 'loc' file that is used for property so there won't be a separate file. See the notes for ODS v3.0.0 
(https://github.com/OasisLMF/OpenDataStandards/releases)

also the updated OED Data spec for v3 can be found here:

(https://github.com/OasisLMF/OpenDataStandards/tree/release/3.0.0/OpenExposureData/Docs)
